#!/bin/bash
#日志功能
if [  -e $PWD/lib/newton-log ]
then	
	source $PWD/lib/newton-log
else
	echo -e "\033[41;37m $PWD/lib/newton-log is not exist. \033[0m"
	exit 1
fi

#输入环境变量
if [  -e $PWD/lib/installrc ]
then	
	source $PWD/lib/installrc 
else
	echo -e "\033[41;37m $PWD/lib/installrc is not exist. \033[0m"
	exit 1
fi
#判断执行用户是否为root
USER_N=`whoami`

if  [ ${USER_N}  = root ]
then 
	log_info "execute by root. "
else
	log_error "execute by ${USER_N}"
	echo -e "\033[41;37m you must execute this scritp by root. \033[0m"
	exit
fi

#openstack功能函数
function fn_install_openstack ()
{
cat << EOF
1) Install Controller Node Service.
2) Install Computer Node Service.
3) Install Block Node Service (Cinder).
4) Install Object Node Service (Swift).
5) Install network Node Service.
0) Quit
EOF
read -p "please input one number for install :" install_number
case ${install_number} in
	1)
		fn_install_openstack_controller
		fn_log "fn_install_openstack_controller"
	;;
	2)
		fn_install_openstack_computer
		fn_log "fn_install_openstack_computer"
	;;
	3)
		fn_install_openstack_block
		fn_log "fn_install_openstack_block"
	;;
	4)
		fn_install_openstack_object
		fn_log "fn_install_openstack_object"
	;;
	5)
		fn_install_openstack_netwok
		fn_log "fn_install_openstack_netwok"
	;;
	0)
		exit 1
	;;
	*)
		echo -e "\033[41;37m please input one number. \033[0m"
		fn_install_openstack
	;;
esac 

}

#controller功能函数
function fn_install_openstack_controller ()
{
cat << EOF
1) Configure System Environment.
2) Install Mariadb and Rabbitmq-server.
3) Install Keystone.
4) Install Glance.
5) Install Nova.
6) Install Cinder.
7) Install Neutron.
8) Install Dashboard.
9) Install Ceilometer.
10) Install Heat.
11) Install Swift.
20) Install All
0) Back
EOF
read -p "please input one number for install :" install_number
case ${install_number} in
	1)
		$PWD/etc/presystem
		fn_log "$PWD/etc/presystem"
		fn_install_openstack_controller
	;;
	2)
		$PWD/etc/install_mariadb
		fn_log "$PWD/etc/install_mariadb"
		fn_install_openstack_controller
	;;
	3)
		$PWD/etc/install_keystone
		fn_log "$PWD/etc/install_keystone"
		fn_install_openstack_controller
	;;
	4)
		$PWD/etc/install_glance
		fn_log "$PWD/etc/install_glance"
		fn_install_openstack_controller
	;;
	5)
        $PWD/etc/install_nova  
		fn_log "$PWD/etc/install_nova"
		fn_install_openstack_controller
	;;
	6)
		$PWD/etc/install_cinder
		fn_log "$PWD/etc/install_cinder"
		fn_install_openstack_controller
	;;
	7)
		$PWD/etc/install_neutron_ovs
		fn_log "$PWD/etc/install_neutron_ovs"
		fn_install_openstack_controller
	;;
	8)
		$PWD/etc/install_dashboard
		fn_log "$PWD/etc/install_dashboard"
		fn_install_openstack_controller
	;;
	9)
		$PWD/etc/install_ceilometer_mongodb
		fn_log "$PWD/etc/install_ceilometer_mongodb"
		fn_install_openstack_controller
	;;
	10)
		$PWD/etc/install_heat
		fn_log "$PWD/etc/install_heat"
		fn_install_openstack_controller
	;;
	11)
		$PWD/etc/install_swift
		fn_log "$PWD/etc/install_swift"
		fn_install_openstack_controller
	;;
	12)
	    $PWD/etc/install_gnocchi
		fn_log "$PWD/etc/install_gnocchi"
		fn_install_openstack_controller
	;;
	13)
	    $PWD/etc/install_mistral
		fn_log "$PWD/etc/install_mistral"
		fn_install_openstack_controller
	;;
	20)
		$PWD/etc/presystem
		fn_log "$PWD/etc/presystem"
		$PWD/etc/install_mariadb
		fn_log "$PWD/etc/install_mariadb"
		$PWD/etc/install_keystone
		fn_log "$PWD/etc/install_keystone"
		$PWD/etc/install_glance
		fn_log "$PWD/etc/install_glance"
        $PWD/etc/install_nova  
		fn_log "$PWD/etc/install_nova"
		$PWD/etc/install_cinder
		fn_log "$PWD/etc/install_cinder"
		$PWD/etc/install_neutron_ovs
		fn_log "$PWD/etc/install_neutron_ovs"
		$PWD/etc/install_dashboard
		fn_log "$PWD/etc/install_dashboard"
		$PWD/etc/install_ceilometer_mongodb
		fn_log "$PWD/etc/install_ceilometer_mongodb"
		$PWD/etc/install_heat
		fn_log "$PWD/etc/install_heat."
		$PWD/etc/install_swift
		fn_log "$PWD/etc/install_swift"
		#$PWD/etc/install_gnocchi
		#fn_log "$PWD/etc/install_gnocchi"
		#$PWD/etc/install_mistral
		#fn_log "$PWD/etc/install_mistral"
		
		echo -e "\033[32m ###############################\033[0m"
		echo -e "\033[32m ###   install All Success   ###\033[0m"
		echo -e "\033[32m ###############################\033[0m"
		fn_install_openstack_controller
	;;
	0)
		fn_install_openstack
	;;
	*)
		echo -e "\033[41;37m please input one right number. \033[0m"
		fn_install_openstack_controller
	;;
esac 
}

#computer功能函数
function fn_install_openstack_computer ()
{
cat << EOF
1) Configure System Environment.
2) Install Computer Service.
20) Install All
0) Back
EOF
read -p "please input one number for install :" install_number
case ${install_number} in
	1)
		$PWD/etc/newton-computer_system
		fn_log "$PWD/etc/newton-computer_system"
		fn_install_openstack_computer
	;;
	2)
		$PWD/etc/newton-computer_install_ovs
		fn_log "$PWD/etc/newton-computer_install_ovs"
		fn_install_openstack_computer
	;;
	20) 
	    $PWD/etc/newton-computer_system
		fn_log "$PWD/etc/newton-computer_system"
		$PWD/etc/newton-computer_install_ovs
		fn_log "$PWD/etc/newton-computer_install_ovs"
		echo -e "\033[32m ###############################\033[0m"
		echo -e "\033[32m ###   install All Success   ###\033[0m"
		echo -e "\033[32m ###############################\033[0m"
		fn_install_openstack_computer
	;;
	0)
		fn_install_openstack
	;;
	*)
		echo -e "\033[41;37m please input one number. \033[0m"
		fn_install_openstack_computer
	;;
esac 

}

#block功能函数
function fn_install_openstack_block () {
cat << EOF
1) Configure System Environment.
2) Install Block Service.
20) Install All
0) Back
EOF
read -p "please input one number for install :" install_number
case ${install_number} in
	1)
		$PWD/etc/newton-block_storage_system
		fn_log "$PWD/etc/newton-block_storage_system"
		fn_install_openstack_block
	;;
	2)
		$PWD/etc/newton-block_install
		fn_log "$PWD/etc/newton-block_install"
		fn_install_openstack_block
	;;
	20) 
	    $PWD/etc/newton-block_storage_system
		fn_log "$PWD/etc/newton-block_storage_system"
		$PWD/etc/newton-block_install
		fn_log "$PWD/etc/newton-block_install"
		echo -e "\033[32m ###############################\033[0m"
		echo -e "\033[32m ###   install All Success   ###\033[0m"
		echo -e "\033[32m ###############################\033[0m"
		fn_install_openstack_block
	;;
	0)
		fn_install_openstack
	;;
	*)
		echo -e "\033[41;37m please input one number. \033[0m"
		fn_install_openstack_block
	;;
esac 

}
#object功能函数
function fn_install_openstack_object () {
cat << EOF
1) Configure System Environment.
2) Install Object Service.
20) Install All
0) Back
EOF
read -p "please input one number for install :" install_number
case ${install_number} in
	1)
		$PWD/etc/newton-object_storage_system
		fn_log "$PWD/etc/newton-object_storage_system"
		fn_install_openstack_object
	;;
	2)
		$PWD/etc/newton-object_install
		fn_log "$PWD/etc/newton-object_install"
		fn_install_openstack_object
	;;
	20) 
	    $PWD/etc/newton-object_storage_system
		fn_log "$PWD/etc/newton-object_storage_system"
		$PWD/etc/newton-object_install
		fn_log "$PWD/etc/newton-object_install"
		echo -e "\033[32m ###############################\033[0m"
		echo -e "\033[32m ###   install All Success   ###\033[0m"
		echo -e "\033[32m ###############################\033[0m"
		fn_install_openstack_object
	;;
	0)
		fn_install_openstack
	;;
	*)
		echo -e "\033[41;37m please input one number. \033[0m"
		fn_install_openstack_object
   ;;
esac 

}
#network功能函数
function fn_install_openstack_netwok () {
cat << EOF
1) Configure System Environment.
2) Install network Service.
20) Install All
0) Back
EOF
read -p "please input one number for install :" install_number
case ${install_number} in
	1)
		$PWD/etc/newton-neutron_system
		fn_log "$PWD/etc/newton-neutron_system"
		fn_install_openstack_netwok
	;;
	2)
		$PWD/etc/newton-neutron_install
		fn_log "$PWD/etc/newton-neutron_install"
		fn_install_openstack_netwok
	;;
	20) 
	    $PWD/etc/newton-neutron_system
		fn_log "$PWD/etc/newton-neutron_system"
		$PWD/etc/newton-neutron_install
		fn_log "$PWD/etc/newton-neutron_install"
		echo -e "\033[32m ###############################\033[0m"
		echo -e "\033[32m ###   install All Success   ###\033[0m"
		echo -e "\033[32m ###############################\033[0m"
		fn_install_openstack_netwok
	;;
	0)
		fn_install_openstack
	;;
	*)
		echo -e "\033[41;37m please input one number. \033[0m"
		fn_install_openstack_netwok
   ;;
esac 

}
#openstack函数调用
fn_install_openstack

