#!/bin/bash
#log function
if [  -e $PWD/lib/newton-log ]
then	
	source $PWD/lib/newton-log
else
	echo -e "\033[41;37m $PWD/lib/newton-log is not exist. \033[0m"
	exit 1
fi

#input variable
if [  -e $PWD/lib/installrc ]
then	
	source $PWD/lib/installrc 
else
	echo -e "\033[41;37m $PWD/lib/installrc is not exist. \033[0m"
	exit 1
fi

if [  -e $PWD/lib/SaveRandPasswd ]
then	
	source $PWD/lib/SaveRandPasswd 
else
	echo -e "\033[41;37m $PWD/lib/SaveRandPasswd is not exist. \033[0m"
	exit 1
fi

if [  -e /etc/openstack-newton_tag/config_keystone.tag  ]
then
	echo -e "\033[41;37m Oh no ! you can't execute this script oncontroller.  \033[0m"
	log_error "Oh no ! you can't execute this script oncontroller. "
	exit 1
fi

if [ -f  /etc/openstack-newton_tag/cinder.tag ]
then 
	echo -e "\033[41;37m you had installed cinder service. \033[0m"
	log_info "you had installed cinder service."	
	exit
fi

#test network
function fn_test_network () {
if [ -f $PWD/lib/proxy.sh ]
then 
	source  $PWD/lib/proxy.sh
fi
curl www.baidu.com >/dev/null   
fn_log "curl www.baidu.com >/dev/null"
}

if  [ -f /etc/yum.repos.d/newton.repo ]
then
	log_info " use local yum."
else 
	fn_test_network
fi

function fn_install_openstackcinder () {
yum install -y lvm2   python-keystone python-openstackclient  python-oslo-policy openstack-cinder targetcli python-keystonemiddleware*  
fn_log "yum install -y lvm2 openstack-cinder targetcli python-oslo-policy "
}
OPENSTACKCINDER_COUNT=`rpm -aq |grep openstack-cinder|wc -l`
if [$OPENSTACKCINDER_COUNT -ne 0]
then
     log_info "openstack-cinder had installed."
else
     fn_install_openstackcinder
fi

function fn_install_openstackutils () {
yum clean all && yum install -y openstack-utils
fn_log "yum clean all && yum install -y openstack-utils"
}
OPENSTACKUTILS_COUNT=`rpm -aq |grep openstack-utils|wc -l`
if [$OPENSTACKUTILS_COUNT -ne 0]
then
     log_info "openstack-utils had installed."
else
     fn_install_openstackutils
fi

systemctl enable lvm2-lvmetad.service && systemctl start lvm2-lvmetad.service
fn_log "systemctl enable lvm2-lvmetad.service && systemctl start lvm2-lvmetad.service"

function fn_create_cinder_volumes () {
if [  -z  ${BLOCK_CINDER_DISK} ]
then 
	log_info "there is not disk for cinder."
else
	pvcreate ${BLOCK_CINDER_DISK}  && vgcreate cinder-volumes ${BLOCK_CINDER_DISK}
	fn_log "pvcreate ${BLOCK_CINDER_DISK}  && vgcreate cinder-volumes ${BLOCK_CINDER_DISK}"
fi

}

VOLUNE_NAME=`vgs | grep cinder-volumes | awk -F " " '{print$1}'`
if [ ${VOLUNE_NAME}x = cinder-volumesx ]
then
	log_info "cinder-volumes had created."
else
	fn_create_cinder_volumes
fi

[ -f   /etc/cinder/cinder.conf_bak  ] || cp -a  /etc/cinder/cinder.conf /etc/cinder/cinder.conf_bak && \
openstack-config --set /etc/cinder/cinder.conf  database connection  mysql+pymysql://cinder:${CINDER_PASSWORD}@${HOST_NAME}/cinder   && \
openstack-config --set /etc/cinder/cinder.conf  DEFAULT transport_url rabbit://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${HOST_NAME} && \
openstack-config --set /etc/cinder/cinder.conf  DEFAULT auth_strategy  keystone && \
openstack-config --set /etc/cinder/cinder.conf  keystone_authtoken auth_uri  http://${HOST_NAME}:5000 && \
openstack-config --set /etc/cinder/cinder.conf  keystone_authtoken auth_url  http://${HOST_NAME}:35357 && \
openstack-config --set /etc/cinder/cinder.conf  keystone_authtoken  memcached_servers  ${HOST_NAME}:11211 && \
openstack-config --set /etc/cinder/cinder.conf  keystone_authtoken auth_type  password && \
openstack-config --set /etc/cinder/cinder.conf  keystone_authtoken project_domain_name  Default && \
openstack-config --set /etc/cinder/cinder.conf  keystone_authtoken user_domain_name  Default && \
openstack-config --set /etc/cinder/cinder.conf  keystone_authtoken project_name  service && \
openstack-config --set /etc/cinder/cinder.conf  keystone_authtoken username  cinder && \
openstack-config --set /etc/cinder/cinder.conf  keystone_authtoken password  ${CINDER_PASSWORD} && \
openstack-config --set /etc/cinder/cinder.conf  DEFAULT my_ip  ${BLOCK_MANAGER_IP} && \
openstack-config --set /etc/cinder/cinder.conf  oslo_concurrency lock_path  /var/lib/cinder/tmp && \
openstack-config --set /etc/cinder/cinder.conf  lvm volume_driver  cinder.volume.drivers.lvm.LVMVolumeDriver  && \
openstack-config --set /etc/cinder/cinder.conf  lvm volume_group  cinder-volumes  && \
openstack-config --set /etc/cinder/cinder.conf  lvm iscsi_protocol  iscsi  && \
openstack-config --set /etc/cinder/cinder.conf  lvm iscsi_helper  lioadm  && \
openstack-config --set /etc/cinder/cinder.conf  DEFAULT glance_api_servers  http://${HOST_NAME}:9292  && \
openstack-config --set /etc/cinder/cinder.conf  DEFAULT enabled_backends  lvm
fn_log "openstack-config --set /etc/cinder/cinder.conf "

chown cinder:cinder /etc/cinder/cinder.conf
fn_log "chown cinder:cinder /etc/cinder/cinder.conf"

systemctl enable openstack-cinder-volume.service target.service && systemctl restart openstack-cinder-volume.service target.service
fn_log "systemctl enable openstack-cinder-volume.service target.service && systemctl restart openstack-cinder-volume.service target.service"

cat <<END >/root/admin-openrc.sh
export OS_PROJECT_DOMAIN_NAME=Default
export OS_USER_DOMAIN_NAME=Default
export OS_REGION_NAME=${REGION_NAME}
export OS_PROJECT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=${ADMIN_PASSWD}
export OS_AUTH_URL=http://${HOST_NAME}:35357/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
END

cat <<END >/root/demo-openrc.sh
export OS_PROJECT_DOMAIN_NAME=Default
export OS_USER_DOMAIN_NAME=Default
export OS_REGION_NAME=${REGION_NAME}
export OS_PROJECT_NAME=demo
export OS_USERNAME=demo
export OS_PASSWORD=${DEMO_PASSWD}
export OS_AUTH_URL=http://${HOST_NAME}:5000/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
END

source /root/admin-openrc.sh
fn_log "source /root/admin-openrc.sh"
cinder service-list
fn_log "cinder service-list"

function fn_install_ceilometer () {
openstack-config --set /etc/cinder/cinder.conf  oslo_messaging_notifications driver  messagingv2
fn_log "openstack-config --set /etc/cinder/cinder.conf  oslo_messaging_notifications driver  messagingv2"

if [ -e /etc/systemd/system/multi-user.target.wants/openstack-cinder-api.service  ]
then
	systemctl restart openstack-cinder-volume.service
	fn_log "systemctl restart openstack-cinder-volume.service"
fi
}

source /root/admin-openrc.sh 
fn_log "source /root/admin-openrc.sh "
USER_ceilometer=`openstack user list | grep ceilometer | grep -v ceilometer_domain_admin | awk -F "|" '{print$3}' | awk -F " " '{print$1}'`
if [ ${USER_ceilometer}x = ceilometerx ]
then
	fn_install_ceilometer
	fn_log "fn_install_ceilometer"
else
	log_info "ceilometer had not installed."
fi

echo -e "\033[32m ####################################################### \033[0m"
echo -e "\033[32m ###       Install Cinder Service  Sucessed          ### \033[0m"
echo -e "\033[32m ####################################################### \033[0m"

if  [ ! -d /etc/openstack-newton_tag ]
then 
	mkdir -p /etc/openstack-newton_tag  
fi
echo `date "+%Y-%m-%d %H:%M:%S"` >/etc/openstack-newton_tag/cinder.tag
    
	
	
























